### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by yiyeChen** [ivapylibs/puzzle_solver#34]
Running the command ```from puzzle.runner import RealSolver``` from Surveillance side gives the following error:

> Traceback (most recent call last):
  File "rosbag_runner.py", line 35, in <module>
    from puzzle.runner import RealSolver
  File "/local/dropbox_cyy/Dropbox (GaTech)/ivapylibs/puzzle_solver/puzzle/runner.py", line 33, in <module>
    from puzzle.solver.simple import Simple
  File "/local/dropbox_cyy/Dropbox (GaTech)/ivapylibs/puzzle_solver/puzzle/solver/simple.py", line 24, in <module>
    from puzzleSolver import PuzzlePieces, PuzzleSolver
ModuleNotFoundError: No module named 'puzzleSolver'

**Comment by Uio96** [comment]
Follow the instruction on the README:

```
git clone git@github.com:ADCLab/puzzleSolvers.git
pip3 install -e puzzleSolvers/
```
